apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  selector:
    matchLabels:
      app: auth 
  template:
    metadata:
      labels:
        app : auth
        environment: dev 
    spec:
      containers:
      - name: auth-pod
        image: auth:v0.2
        ports:
        - name:  auth-app-svc
          containerPort: 3001
        env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: DB_PASSWORD
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: DB_PORT
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: DB_DATABASE

---

kind: Service
apiVersion: v1
metadata:
  name:  auth-svc 
spec:
  selector:
    app: auth 
  type:  LoadBalancer
  ports:
  - name:  auth-svc-port
    port:  3001
    targetPort:  auth-app-svc


