definitions:
  data.CreateReq:
    properties:
      title:
        type: string
      user_id:
        type: integer
    type: object
  data.TaskId:
    properties:
      task_id:
        type: string
    type: object
info:
  contact: {}
paths:
  /tasks/create:
    post:
      consumes:
      - application/json
      description: If user is valid, create taskA.
      parameters:
      - description: query params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/data.CreateReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/data.TaskId'
      summary: Create taskA
      tags:
      - tasks
swagger: "2.0"
